"""Add marketplace and user settings

Revision ID: 281b645a0eec
Revises: b2b8bdd8fdaf
Create Date: 2025-08-14 22:26:33.318746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281b645a0eec'
down_revision: Union[str, None] = 'b2b8bdd8fdaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
