"""Add archive ratings system

Revision ID: 8d0b52e93836
Revises: bac5eee022b5
Create Date: 2025-08-10 22:29:55.673046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0b52e93836'
down_revision: Union[str, None] = 'bac5eee022b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archives', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('archives', sa.Column('ratings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archives', 'ratings_count')
    op.drop_column('archives', 'average_rating')
    # ### end Alembic commands ###
